from flask import Flask, request, jsonify, send_from_directory
from flask_cors import CORS
import json
import os
from datetime import datetime

# Serve the game from the `www/` folder so the web assets are the single source of truth.
PROJECT_ROOT = os.path.dirname(os.path.abspath(__file__))
# Prefer platformio/data when present (so compiled/platformio workflow and local server use the same files).
PLATFORMIO_DATA = os.path.join(PROJECT_ROOT, 'platformio', 'data')
WWW_DIR = os.path.join(PROJECT_ROOT, 'www')
# Choose STATIC_DIR: platformio/data if it exists and is not empty, otherwise www/
if os.path.isdir(PLATFORMIO_DATA) and len(os.listdir(PLATFORMIO_DATA)) > 0:
    STATIC_DIR = PLATFORMIO_DATA
else:
    STATIC_DIR = WWW_DIR

app = Flask(__name__)
CORS(app)  # Allow cross-origin requests

# Store highscores inside the www folder so the web client and the ESP32 upload script
# can use the same source file. This file is considered the authoritative highscores file
# for local development; platformio/data/ is generated by upload_data.py and ignored in git.
HIGHSCORE_FILE = os.path.join(STATIC_DIR, 'highscore.json')


def load_highscores():
    """Load highscores from JSON file inside www/"""
    if os.path.exists(HIGHSCORE_FILE):
        try:
            with open(HIGHSCORE_FILE, 'r') as f:
                data = json.load(f)
                return data.get('highscores', [])
        except Exception:
            return []
    return []


def save_highscores(highscores):
    """Save highscores to JSON file inside www/"""
    os.makedirs(STATIC_DIR, exist_ok=True)
    data = {'highscores': highscores}
    with open(HIGHSCORE_FILE, 'w') as f:
        json.dump(data, f, indent=2)


@app.route('/api/highscores', methods=['GET'])
def get_highscores():
    """Get all highscores"""
    highscores = load_highscores()
    return jsonify({'highscores': highscores})


@app.route('/api/highscores', methods=['POST'])
def add_highscore():
    """Add a new highscore or accept bulk highscores"""
    try:
        data = request.get_json() or {}

        # Handle both single highscore and highscores array
        if 'highscores' in data:
            highscores = data['highscores']
            # Limit to top 10000 scores to prevent unlimited growth
            highscores.sort(key=lambda x: x.get('score', 0), reverse=True)
            highscores = highscores[:10000]
            save_highscores(highscores)
            return jsonify({'success': True, 'message': 'Highscores saved successfully'})
        else:
            # Single highscore submission
            name = data.get('name', 'Anonymous')
            score = data.get('score', 0)
            date = data.get('date', datetime.now().isoformat())
            player_fingerprint = data.get('playerFingerprint', 'unknown')
            
            # Validate inputs
            if not isinstance(score, (int, float)) or score < 0:
                return jsonify({'success': False, 'error': 'Invalid score'}), 400
            
            if not isinstance(name, str) or len(name) > 15:
                return jsonify({'success': False, 'error': 'Invalid name'}), 400
            
            # Sanitize name server-side
            import re
            name = re.sub(r'[<>]', '', name)  # Remove HTML tags
            name = re.sub(r'[^\w\s\-_.]', '', name)  # Keep only safe characters
            name = name[:15]  # Enforce max length
            
            if not name.strip():
                name = 'Anonymous'

            highscores = load_highscores()

            new_highscore = {
                'name': name,
                'score': int(score),  # Ensure score is integer
                'date': date,
                'playerFingerprint': player_fingerprint
            }

            highscores.append(new_highscore)
            # Sort by score in descending order (highest first)
            highscores.sort(key=lambda x: x.get('score', 0), reverse=True)
            
            # Keep only top 10000 scores
            highscores = highscores[:10000]

            save_highscores(highscores)
            return jsonify({'success': True, 'message': 'Highscore added successfully'})

    except Exception as e:
        return jsonify({'success': False, 'error': str(e)}), 500


@app.route('/')
def serve_game():
    """Serve the main game file from the www folder"""
    return send_from_directory(STATIC_DIR, 'index.html')


@app.route('/<path:filename>')
def serve_static(filename):
    """Serve static files (CSS, JS, images) from the www folder"""
    return send_from_directory(STATIC_DIR, filename)


if __name__ == '__main__':
    # Run the local dev server for working on the web client at http://localhost:5000
    app.run(debug=True, host='127.0.0.1', port=5000)